version: '3.8'

services:
  mcp-pdf-server:
    build: .
    container_name: mcp-pdf-converter
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - OUTPUT_DIR=/app/output
    stdin_open: true
    tty: true